name: Commit Linting

on:
    pull_request:
        types: [ opened, synchronize, reopened ]
    push:
        branches: [ release-* ]

jobs:
    commit-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Lint Commits
              uses: webiny/action-conventional-commits@v1.3.0
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                allowed-commit-types: "feat,fix,docs,style,refactor,test,chore,perf"