name: Release
on:
    pull_request:
        types: [ closed ]
        branches: [ release ]

jobs:
    changelog:
        if: ${{ github.event.pull_request.merged == true }}
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
                fetch-depth: 0
          - name: Conventional Changelog Action
            id: conventional-changelog
            uses: TriPSs/conventional-changelog-action@v5
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

          - name: Create Release
            uses: actions/create-release@v1
            if: ${{ steps.conventional-changelog.outputs.skipped == 'false' }}
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                tag_name: ${{ steps.conventional-changelog.outputs.tag }}
                release_name: ${{ steps.conventional-changelog.outputs.tag }}
                body: ${{ steps.conventional-changelog.outputs.clean_changelog }}