name: Release

on:
  push:
    branches: [ release ]

jobs:
    Release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Checkout
              run: |
                git config user.name "GitHub Actions"
                git config user.email "<>"

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'

            - name: Bump version
              id: version
              uses: qzb/standard-version-action@v1.0.5

            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Create Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ steps.package-version.outputs.current-version }}
                release_name: ${{ steps.package-version.outputs.current-version }}
                draft: false
                prerelease: false