name: Release

on:
  push:
    branches: [ release ]

jobs:
    Release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Checkout
              run: |
                git config user.name "GitHub Actions"
                git config user.email "<>"

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'

            - name: Install Dependencies
              run: npm install

            - name: Bump Version and Update Changelog
              id: version
              run: |
                if git log -1 --pretty=%B | grep -iq "BREAKING CHANGE"; then
                  npx standard-version --release-as major
                else
                  npx standard-version
                fi
                git push --follow-tags origin release

            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Create Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ steps.package-version.outputs.current-version }}
                release_name: ${{ steps.package-version.outputs.current-version }}
                draft: false
                prerelease: false