name: Release Workflow

on:
    push:
        branches: [ release ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run release script
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: python changelog_generator.py