name: Semantic Release

on:
    pull_request:
        types: [ closed ]
        branches: [ release-* ]

jobs:
    semantic-release:
        if: ${{ github.event.pull_request.merged == true }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Semantic Release
              uses: python-semantic-release/python-semantic-release@v9.21.0
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                changelog: true
                commit: true
                push: true
                tag: true
                vcs_release: true
                